/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 4.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountLastSuccessSyncEntity,
  AccountTransactionsSyncJobPayload,
  OnBankAccountCreatedPayload,
  RawAccountEntity,
} from '../models/index';
import {
    AccountLastSuccessSyncEntityFromJSON,
    AccountLastSuccessSyncEntityToJSON,
    AccountTransactionsSyncJobPayloadFromJSON,
    AccountTransactionsSyncJobPayloadToJSON,
    OnBankAccountCreatedPayloadFromJSON,
    OnBankAccountCreatedPayloadToJSON,
    RawAccountEntityFromJSON,
    RawAccountEntityToJSON,
} from '../models/index';

export interface FindAllAccountsRequest {
    itemId: string;
}

export interface GetLastAccountSuccessSyncRequest {
    accountId: string;
}

export interface StartAccountTransactionsSyncRequest {
    onBankAccountCreatedPayload: OnBankAccountCreatedPayload;
}

export interface SyncAccountTransactionsRequest {
    accountTransactionsSyncJobPayload: AccountTransactionsSyncJobPayload;
}

/**
 * AccountsApi - interface
 * 
 * @export
 * @interface AccountsApiInterface
 */
export interface AccountsApiInterface {
    /**
     * 
     * @summary Find all accounts for a given item
     * @param {string} itemId The item id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    findAllAccountsRaw(requestParameters: FindAllAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RawAccountEntity>>>;

    /**
     * Find all accounts for a given item
     */
    findAllAccounts(requestParameters: FindAllAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RawAccountEntity>>;

    /**
     * 
     * @summary Get the last successful sync date for an account
     * @param {string} accountId The sofia account id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    getLastAccountSuccessSyncRaw(requestParameters: GetLastAccountSuccessSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountLastSuccessSyncEntity>>;

    /**
     * Get the last successful sync date for an account
     */
    getLastAccountSuccessSync(requestParameters: GetLastAccountSuccessSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountLastSuccessSyncEntity>;

    /**
     * 
     * @summary Start account transactions sync
     * @param {OnBankAccountCreatedPayload} onBankAccountCreatedPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    startAccountTransactionsSyncRaw(requestParameters: StartAccountTransactionsSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Start account transactions sync
     */
    startAccountTransactionsSync(requestParameters: StartAccountTransactionsSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Process account transactions sync job
     * @param {AccountTransactionsSyncJobPayload} accountTransactionsSyncJobPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    syncAccountTransactionsRaw(requestParameters: SyncAccountTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Process account transactions sync job
     */
    syncAccountTransactions(requestParameters: SyncAccountTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class AccountsApi extends runtime.BaseAPI implements AccountsApiInterface {

    /**
     * Find all accounts for a given item
     */
    async findAllAccountsRaw(requestParameters: FindAllAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RawAccountEntity>>> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling findAllAccounts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/external/open-finance/items/{itemId}/accounts`;
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RawAccountEntityFromJSON));
    }

    /**
     * Find all accounts for a given item
     */
    async findAllAccounts(requestParameters: FindAllAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RawAccountEntity>> {
        const response = await this.findAllAccountsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the last successful sync date for an account
     */
    async getLastAccountSuccessSyncRaw(requestParameters: GetLastAccountSuccessSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountLastSuccessSyncEntity>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getLastAccountSuccessSync().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/external/open-finance/accounts/{accountId}/last-success-sync`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountLastSuccessSyncEntityFromJSON(jsonValue));
    }

    /**
     * Get the last successful sync date for an account
     */
    async getLastAccountSuccessSync(requestParameters: GetLastAccountSuccessSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountLastSuccessSyncEntity> {
        const response = await this.getLastAccountSuccessSyncRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start account transactions sync
     */
    async startAccountTransactionsSyncRaw(requestParameters: StartAccountTransactionsSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['onBankAccountCreatedPayload'] == null) {
            throw new runtime.RequiredError(
                'onBankAccountCreatedPayload',
                'Required parameter "onBankAccountCreatedPayload" was null or undefined when calling startAccountTransactionsSync().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/internal/open-finance/accounts/on/bank-account-created`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OnBankAccountCreatedPayloadToJSON(requestParameters['onBankAccountCreatedPayload']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Start account transactions sync
     */
    async startAccountTransactionsSync(requestParameters: StartAccountTransactionsSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.startAccountTransactionsSyncRaw(requestParameters, initOverrides);
    }

    /**
     * Process account transactions sync job
     */
    async syncAccountTransactionsRaw(requestParameters: SyncAccountTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['accountTransactionsSyncJobPayload'] == null) {
            throw new runtime.RequiredError(
                'accountTransactionsSyncJobPayload',
                'Required parameter "accountTransactionsSyncJobPayload" was null or undefined when calling syncAccountTransactions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/internal/queues/account-transactions-sync`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountTransactionsSyncJobPayloadToJSON(requestParameters['accountTransactionsSyncJobPayload']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Process account transactions sync job
     */
    async syncAccountTransactions(requestParameters: SyncAccountTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.syncAccountTransactionsRaw(requestParameters, initOverrides);
    }

}
