/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExceptionResponseEntity,
  IntegrationPreviewEntity,
} from '../models/index';
import {
    ExceptionResponseEntityFromJSON,
    ExceptionResponseEntityToJSON,
    IntegrationPreviewEntityFromJSON,
    IntegrationPreviewEntityToJSON,
} from '../models/index';

/**
 * IntegrationsApi - interface
 * 
 * @export
 * @interface IntegrationsApiInterface
 */
export interface IntegrationsApiInterface {
    /**
     * Returns a list of all integrations with their details and availability status
     * @summary Get integrations preview
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    getIntegrationPreviewsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IntegrationPreviewEntity>>>;

    /**
     * Returns a list of all integrations with their details and availability status
     * Get integrations preview
     */
    getIntegrationPreviews(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IntegrationPreviewEntity>>;

}

/**
 * 
 */
export class IntegrationsApi extends runtime.BaseAPI implements IntegrationsApiInterface {

    /**
     * Returns a list of all integrations with their details and availability status
     * Get integrations preview
     */
    async getIntegrationPreviewsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IntegrationPreviewEntity>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/external/integrations/preview`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IntegrationPreviewEntityFromJSON));
    }

    /**
     * Returns a list of all integrations with their details and availability status
     * Get integrations preview
     */
    async getIntegrationPreviews(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IntegrationPreviewEntity>> {
        const response = await this.getIntegrationPreviewsRaw(initOverrides);
        return await response.value();
    }

}
