/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateConnectTokenResponseBodyDto,
  ExceptionResponseEntity,
} from '../models/index';
import {
    CreateConnectTokenResponseBodyDtoFromJSON,
    CreateConnectTokenResponseBodyDtoToJSON,
    ExceptionResponseEntityFromJSON,
    ExceptionResponseEntityToJSON,
} from '../models/index';

/**
 * PluggyApi - interface
 * 
 * @export
 * @interface PluggyApiInterface
 */
export interface PluggyApiInterface {
    /**
     * 
     * @summary Create a connect token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PluggyApiInterface
     */
    createConnectTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateConnectTokenResponseBodyDto>>;

    /**
     * Create a connect token
     */
    createConnectToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateConnectTokenResponseBodyDto>;

}

/**
 * 
 */
export class PluggyApi extends runtime.BaseAPI implements PluggyApiInterface {

    /**
     * Create a connect token
     */
    async createConnectTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateConnectTokenResponseBodyDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/external/open-finance/pluggy/connect-token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateConnectTokenResponseBodyDtoFromJSON(jsonValue));
    }

    /**
     * Create a connect token
     */
    async createConnectToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateConnectTokenResponseBodyDto> {
        const response = await this.createConnectTokenRaw(initOverrides);
        return await response.value();
    }

}
