/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OnBankAccountCreatedPayloadRequester } from './OnBankAccountCreatedPayloadRequester';
import {
    OnBankAccountCreatedPayloadRequesterFromJSON,
    OnBankAccountCreatedPayloadRequesterFromJSONTyped,
    OnBankAccountCreatedPayloadRequesterToJSON,
    OnBankAccountCreatedPayloadRequesterToJSONTyped,
} from './OnBankAccountCreatedPayloadRequester';

/**
 * 
 * @export
 * @interface AccountTransactionPageSyncJobPayload
 */
export interface AccountTransactionPageSyncJobPayload {
    /**
     * 
     * @type {OnBankAccountCreatedPayloadRequester}
     * @memberof AccountTransactionPageSyncJobPayload
     */
    requester: OnBankAccountCreatedPayloadRequester;
    /**
     * 
     * @type {string}
     * @memberof AccountTransactionPageSyncJobPayload
     */
    accountTransactionsSyncJobExecutionId: string;
    /**
     * 
     * @type {number}
     * @memberof AccountTransactionPageSyncJobPayload
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof AccountTransactionPageSyncJobPayload
     */
    pageSize: number;
}

/**
 * Check if a given object implements the AccountTransactionPageSyncJobPayload interface.
 */
export function instanceOfAccountTransactionPageSyncJobPayload(value: object): value is AccountTransactionPageSyncJobPayload {
    if (!('requester' in value) || value['requester'] === undefined) return false;
    if (!('accountTransactionsSyncJobExecutionId' in value) || value['accountTransactionsSyncJobExecutionId'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    return true;
}

export function AccountTransactionPageSyncJobPayloadFromJSON(json: any): AccountTransactionPageSyncJobPayload {
    return AccountTransactionPageSyncJobPayloadFromJSONTyped(json, false);
}

export function AccountTransactionPageSyncJobPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountTransactionPageSyncJobPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'requester': OnBankAccountCreatedPayloadRequesterFromJSON(json['requester']),
        'accountTransactionsSyncJobExecutionId': json['accountTransactionsSyncJobExecutionId'],
        'pageNumber': json['pageNumber'],
        'pageSize': json['pageSize'],
    };
}

export function AccountTransactionPageSyncJobPayloadToJSON(json: any): AccountTransactionPageSyncJobPayload {
    return AccountTransactionPageSyncJobPayloadToJSONTyped(json, false);
}

export function AccountTransactionPageSyncJobPayloadToJSONTyped(value?: AccountTransactionPageSyncJobPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requester': OnBankAccountCreatedPayloadRequesterToJSON(value['requester']),
        'accountTransactionsSyncJobExecutionId': value['accountTransactionsSyncJobExecutionId'],
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
    };
}

