/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OnBankAccountCreatedPayloadRequester } from './OnBankAccountCreatedPayloadRequester';
import {
    OnBankAccountCreatedPayloadRequesterFromJSON,
    OnBankAccountCreatedPayloadRequesterFromJSONTyped,
    OnBankAccountCreatedPayloadRequesterToJSON,
    OnBankAccountCreatedPayloadRequesterToJSONTyped,
} from './OnBankAccountCreatedPayloadRequester';

/**
 * 
 * @export
 * @interface AccountTransactionsSyncJobPayload
 */
export interface AccountTransactionsSyncJobPayload {
    /**
     * 
     * @type {OnBankAccountCreatedPayloadRequester}
     * @memberof AccountTransactionsSyncJobPayload
     */
    requester: OnBankAccountCreatedPayloadRequester;
    /**
     * 
     * @type {string}
     * @memberof AccountTransactionsSyncJobPayload
     */
    accountTransactionsSyncJobRequestId: string;
}

/**
 * Check if a given object implements the AccountTransactionsSyncJobPayload interface.
 */
export function instanceOfAccountTransactionsSyncJobPayload(value: object): value is AccountTransactionsSyncJobPayload {
    if (!('requester' in value) || value['requester'] === undefined) return false;
    if (!('accountTransactionsSyncJobRequestId' in value) || value['accountTransactionsSyncJobRequestId'] === undefined) return false;
    return true;
}

export function AccountTransactionsSyncJobPayloadFromJSON(json: any): AccountTransactionsSyncJobPayload {
    return AccountTransactionsSyncJobPayloadFromJSONTyped(json, false);
}

export function AccountTransactionsSyncJobPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountTransactionsSyncJobPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'requester': OnBankAccountCreatedPayloadRequesterFromJSON(json['requester']),
        'accountTransactionsSyncJobRequestId': json['accountTransactionsSyncJobRequestId'],
    };
}

export function AccountTransactionsSyncJobPayloadToJSON(json: any): AccountTransactionsSyncJobPayload {
    return AccountTransactionsSyncJobPayloadToJSONTyped(json, false);
}

export function AccountTransactionsSyncJobPayloadToJSONTyped(value?: AccountTransactionsSyncJobPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requester': OnBankAccountCreatedPayloadRequesterToJSON(value['requester']),
        'accountTransactionsSyncJobRequestId': value['accountTransactionsSyncJobRequestId'],
    };
}

