/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountLastSuccessSyncEntityData
 */
export interface AccountLastSuccessSyncEntityData {
    /**
     * 
     * @type {string}
     * @memberof AccountLastSuccessSyncEntityData
     */
    accountTransactionsSyncJobRequestId: string;
    /**
     * 
     * @type {string}
     * @memberof AccountLastSuccessSyncEntityData
     */
    accountTransactionsSyncJobExecutionId: string;
    /**
     * 
     * @type {any}
     * @memberof AccountLastSuccessSyncEntityData
     */
    finishedAt: any | null;
    /**
     * 
     * @type {number}
     * @memberof AccountLastSuccessSyncEntityData
     */
    nTotalItems: number;
}

/**
 * Check if a given object implements the AccountLastSuccessSyncEntityData interface.
 */
export function instanceOfAccountLastSuccessSyncEntityData(value: object): value is AccountLastSuccessSyncEntityData {
    if (!('accountTransactionsSyncJobRequestId' in value) || value['accountTransactionsSyncJobRequestId'] === undefined) return false;
    if (!('accountTransactionsSyncJobExecutionId' in value) || value['accountTransactionsSyncJobExecutionId'] === undefined) return false;
    if (!('finishedAt' in value) || value['finishedAt'] === undefined) return false;
    if (!('nTotalItems' in value) || value['nTotalItems'] === undefined) return false;
    return true;
}

export function AccountLastSuccessSyncEntityDataFromJSON(json: any): AccountLastSuccessSyncEntityData {
    return AccountLastSuccessSyncEntityDataFromJSONTyped(json, false);
}

export function AccountLastSuccessSyncEntityDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountLastSuccessSyncEntityData {
    if (json == null) {
        return json;
    }
    return {
        
        'accountTransactionsSyncJobRequestId': json['accountTransactionsSyncJobRequestId'],
        'accountTransactionsSyncJobExecutionId': json['accountTransactionsSyncJobExecutionId'],
        'finishedAt': json['finishedAt'],
        'nTotalItems': json['nTotalItems'],
    };
}

export function AccountLastSuccessSyncEntityDataToJSON(json: any): AccountLastSuccessSyncEntityData {
    return AccountLastSuccessSyncEntityDataToJSONTyped(json, false);
}

export function AccountLastSuccessSyncEntityDataToJSONTyped(value?: AccountLastSuccessSyncEntityData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountTransactionsSyncJobRequestId': value['accountTransactionsSyncJobRequestId'],
        'accountTransactionsSyncJobExecutionId': value['accountTransactionsSyncJobExecutionId'],
        'finishedAt': value['finishedAt'],
        'nTotalItems': value['nTotalItems'],
    };
}

