/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountLastSuccessSyncEntityData } from './AccountLastSuccessSyncEntityData';
import {
    AccountLastSuccessSyncEntityDataFromJSON,
    AccountLastSuccessSyncEntityDataFromJSONTyped,
    AccountLastSuccessSyncEntityDataToJSON,
    AccountLastSuccessSyncEntityDataToJSONTyped,
} from './AccountLastSuccessSyncEntityData';

/**
 * 
 * @export
 * @interface AccountLastSuccessSyncEntity
 */
export interface AccountLastSuccessSyncEntity {
    /**
     * 
     * @type {boolean}
     * @memberof AccountLastSuccessSyncEntity
     */
    _exists: boolean;
    /**
     * 
     * @type {AccountLastSuccessSyncEntityData}
     * @memberof AccountLastSuccessSyncEntity
     */
    data: AccountLastSuccessSyncEntityData | null;
}

/**
 * Check if a given object implements the AccountLastSuccessSyncEntity interface.
 */
export function instanceOfAccountLastSuccessSyncEntity(value: object): value is AccountLastSuccessSyncEntity {
    if (!('_exists' in value) || value['_exists'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AccountLastSuccessSyncEntityFromJSON(json: any): AccountLastSuccessSyncEntity {
    return AccountLastSuccessSyncEntityFromJSONTyped(json, false);
}

export function AccountLastSuccessSyncEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountLastSuccessSyncEntity {
    if (json == null) {
        return json;
    }
    return {
        
        '_exists': json['exists'],
        'data': AccountLastSuccessSyncEntityDataFromJSON(json['data']),
    };
}

export function AccountLastSuccessSyncEntityToJSON(json: any): AccountLastSuccessSyncEntity {
    return AccountLastSuccessSyncEntityToJSONTyped(json, false);
}

export function AccountLastSuccessSyncEntityToJSONTyped(value?: AccountLastSuccessSyncEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exists': value['_exists'],
        'data': AccountLastSuccessSyncEntityDataToJSON(value['data']),
    };
}

