/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CacheSetDto
 */
export interface CacheSetDto {
    /**
     * String value to cache
     * @type {string}
     * @memberof CacheSetDto
     */
    value: string;
}

/**
 * Check if a given object implements the CacheSetDto interface.
 */
export function instanceOfCacheSetDto(value: object): value is CacheSetDto {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CacheSetDtoFromJSON(json: any): CacheSetDto {
    return CacheSetDtoFromJSONTyped(json, false);
}

export function CacheSetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheSetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function CacheSetDtoToJSON(json: any): CacheSetDto {
    return CacheSetDtoToJSONTyped(json, false);
}

export function CacheSetDtoToJSONTyped(value?: CacheSetDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

