/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CacheGetResponseDto
 */
export interface CacheGetResponseDto {
    /**
     * Cached string value, null if not found
     * @type {string}
     * @memberof CacheGetResponseDto
     */
    value: string | null;
}

/**
 * Check if a given object implements the CacheGetResponseDto interface.
 */
export function instanceOfCacheGetResponseDto(value: object): value is CacheGetResponseDto {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CacheGetResponseDtoFromJSON(json: any): CacheGetResponseDto {
    return CacheGetResponseDtoFromJSONTyped(json, false);
}

export function CacheGetResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheGetResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function CacheGetResponseDtoToJSON(json: any): CacheGetResponseDto {
    return CacheGetResponseDtoToJSONTyped(json, false);
}

export function CacheGetResponseDtoToJSONTyped(value?: CacheGetResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

