/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateConnectTokenResponseBodyDto
 */
export interface CreateConnectTokenResponseBodyDto {
    /**
     * 
     * @type {string}
     * @memberof CreateConnectTokenResponseBodyDto
     */
    connectToken: string;
}

/**
 * Check if a given object implements the CreateConnectTokenResponseBodyDto interface.
 */
export function instanceOfCreateConnectTokenResponseBodyDto(value: object): value is CreateConnectTokenResponseBodyDto {
    if (!('connectToken' in value) || value['connectToken'] === undefined) return false;
    return true;
}

export function CreateConnectTokenResponseBodyDtoFromJSON(json: any): CreateConnectTokenResponseBodyDto {
    return CreateConnectTokenResponseBodyDtoFromJSONTyped(json, false);
}

export function CreateConnectTokenResponseBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConnectTokenResponseBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'connectToken': json['connectToken'],
    };
}

export function CreateConnectTokenResponseBodyDtoToJSON(json: any): CreateConnectTokenResponseBodyDto {
    return CreateConnectTokenResponseBodyDtoToJSONTyped(json, false);
}

export function CreateConnectTokenResponseBodyDtoToJSONTyped(value?: CreateConnectTokenResponseBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connectToken': value['connectToken'],
    };
}

