/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForwardedEmailEntityPopulatedAttachmentsInner
 */
export interface ForwardedEmailEntityPopulatedAttachmentsInner {
    /**
     * Identificador do arquivo.
     * @type {string}
     * @memberof ForwardedEmailEntityPopulatedAttachmentsInner
     */
    id: string;
    /**
     * Identificador da organização dona do arquivo.
     * @type {string}
     * @memberof ForwardedEmailEntityPopulatedAttachmentsInner
     */
    ownerOrganization: string;
    /**
     * Nome original do arquivo.
     * @type {string}
     * @memberof ForwardedEmailEntityPopulatedAttachmentsInner
     */
    originalFileName: string;
    /**
     * Tipo MIME do arquivo.
     * @type {string}
     * @memberof ForwardedEmailEntityPopulatedAttachmentsInner
     */
    mimeType: string;
    /**
     * Tamanho do arquivo em bytes.
     * @type {number}
     * @memberof ForwardedEmailEntityPopulatedAttachmentsInner
     */
    size: number;
    /**
     * Tipo do arquivo.
     * @type {string}
     * @memberof ForwardedEmailEntityPopulatedAttachmentsInner
     */
    fileType: ForwardedEmailEntityPopulatedAttachmentsInnerFileTypeEnum;
    /**
     * Nome do objeto no storage.
     * @type {string}
     * @memberof ForwardedEmailEntityPopulatedAttachmentsInner
     */
    objectName: string;
    /**
     * Status do arquivo.
     * @type {string}
     * @memberof ForwardedEmailEntityPopulatedAttachmentsInner
     */
    status: ForwardedEmailEntityPopulatedAttachmentsInnerStatusEnum;
    /**
     * Legenda do arquivo.
     * @type {string}
     * @memberof ForwardedEmailEntityPopulatedAttachmentsInner
     */
    caption?: string | null;
    /**
     * Data de criação do arquivo.
     * @type {any}
     * @memberof ForwardedEmailEntityPopulatedAttachmentsInner
     */
    createdAt: any | null;
    /**
     * Data de atualização do arquivo.
     * @type {any}
     * @memberof ForwardedEmailEntityPopulatedAttachmentsInner
     */
    updatedAt: any | null;
    /**
     * Data de exclusão do arquivo.
     * @type {any}
     * @memberof ForwardedEmailEntityPopulatedAttachmentsInner
     */
    deletedAt?: any | null;
    /**
     * URL do arquivo.
     * @type {string}
     * @memberof ForwardedEmailEntityPopulatedAttachmentsInner
     */
    url: string;
    /**
     * URL assinada do arquivo.
     * @type {string}
     * @memberof ForwardedEmailEntityPopulatedAttachmentsInner
     */
    signedUrl: string;
}


/**
 * @export
 */
export const ForwardedEmailEntityPopulatedAttachmentsInnerFileTypeEnum = {
    Default: 'DEFAULT',
    FinancialRecord: 'FINANCIAL_RECORD',
    Export: 'EXPORT',
    InstallmentFinancialRecord: 'INSTALLMENT_FINANCIAL_RECORD',
    RecurringFinancialRecord: 'RECURRING_FINANCIAL_RECORD',
    Ofx: 'OFX',
    ExtractFinancialRecordFromFile: 'EXTRACT_FINANCIAL_RECORD_FROM_FILE',
    ExtractContactFromFile: 'EXTRACT_CONTACT_FROM_FILE',
    FinancialRecordsBulkCreate: 'FINANCIAL_RECORDS_BULK_CREATE',
    ContactsBulkCreate: 'CONTACTS_BULK_CREATE',
    FinancialRecordsBulkCreateExtractionInput: 'FINANCIAL_RECORDS_BULK_CREATE_EXTRACTION_INPUT',
    FinancialRecordsBulkCreateExtractionOutput: 'FINANCIAL_RECORDS_BULK_CREATE_EXTRACTION_OUTPUT',
    ContactsBulkCreateExtractionInput: 'CONTACTS_BULK_CREATE_EXTRACTION_INPUT',
    ContactsBulkCreateExtractionOutput: 'CONTACTS_BULK_CREATE_EXTRACTION_OUTPUT',
    SevenDaysTempFile: 'SEVEN_DAYS_TEMP_FILE',
    WhatsappMessageFile: 'WHATSAPP_MESSAGE_FILE',
    EmailForwardingIntegration: 'EMAIL_FORWARDING_INTEGRATION'
} as const;
export type ForwardedEmailEntityPopulatedAttachmentsInnerFileTypeEnum = typeof ForwardedEmailEntityPopulatedAttachmentsInnerFileTypeEnum[keyof typeof ForwardedEmailEntityPopulatedAttachmentsInnerFileTypeEnum];

/**
 * @export
 */
export const ForwardedEmailEntityPopulatedAttachmentsInnerStatusEnum = {
    Pending: 'PENDING',
    Completed: 'COMPLETED',
    Failed: 'FAILED',
    Deleted: 'DELETED'
} as const;
export type ForwardedEmailEntityPopulatedAttachmentsInnerStatusEnum = typeof ForwardedEmailEntityPopulatedAttachmentsInnerStatusEnum[keyof typeof ForwardedEmailEntityPopulatedAttachmentsInnerStatusEnum];


/**
 * Check if a given object implements the ForwardedEmailEntityPopulatedAttachmentsInner interface.
 */
export function instanceOfForwardedEmailEntityPopulatedAttachmentsInner(value: object): value is ForwardedEmailEntityPopulatedAttachmentsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerOrganization' in value) || value['ownerOrganization'] === undefined) return false;
    if (!('originalFileName' in value) || value['originalFileName'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('fileType' in value) || value['fileType'] === undefined) return false;
    if (!('objectName' in value) || value['objectName'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('signedUrl' in value) || value['signedUrl'] === undefined) return false;
    return true;
}

export function ForwardedEmailEntityPopulatedAttachmentsInnerFromJSON(json: any): ForwardedEmailEntityPopulatedAttachmentsInner {
    return ForwardedEmailEntityPopulatedAttachmentsInnerFromJSONTyped(json, false);
}

export function ForwardedEmailEntityPopulatedAttachmentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForwardedEmailEntityPopulatedAttachmentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerOrganization': json['ownerOrganization'],
        'originalFileName': json['originalFileName'],
        'mimeType': json['mimeType'],
        'size': json['size'],
        'fileType': json['fileType'],
        'objectName': json['objectName'],
        'status': json['status'],
        'caption': json['caption'] == null ? undefined : json['caption'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'deletedAt': json['deletedAt'] == null ? undefined : json['deletedAt'],
        'url': json['url'],
        'signedUrl': json['signedUrl'],
    };
}

export function ForwardedEmailEntityPopulatedAttachmentsInnerToJSON(json: any): ForwardedEmailEntityPopulatedAttachmentsInner {
    return ForwardedEmailEntityPopulatedAttachmentsInnerToJSONTyped(json, false);
}

export function ForwardedEmailEntityPopulatedAttachmentsInnerToJSONTyped(value?: ForwardedEmailEntityPopulatedAttachmentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ownerOrganization': value['ownerOrganization'],
        'originalFileName': value['originalFileName'],
        'mimeType': value['mimeType'],
        'size': value['size'],
        'fileType': value['fileType'],
        'objectName': value['objectName'],
        'status': value['status'],
        'caption': value['caption'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'deletedAt': value['deletedAt'],
        'url': value['url'],
        'signedUrl': value['signedUrl'],
    };
}

