/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForwardedEmailEntityEnvelope
 */
export interface ForwardedEmailEntityEnvelope {
    /**
     * 
     * @type {Array<string>}
     * @memberof ForwardedEmailEntityEnvelope
     */
    to: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ForwardedEmailEntityEnvelope
     */
    from: string;
}

/**
 * Check if a given object implements the ForwardedEmailEntityEnvelope interface.
 */
export function instanceOfForwardedEmailEntityEnvelope(value: object): value is ForwardedEmailEntityEnvelope {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    return true;
}

export function ForwardedEmailEntityEnvelopeFromJSON(json: any): ForwardedEmailEntityEnvelope {
    return ForwardedEmailEntityEnvelopeFromJSONTyped(json, false);
}

export function ForwardedEmailEntityEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForwardedEmailEntityEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'from': json['from'],
    };
}

export function ForwardedEmailEntityEnvelopeToJSON(json: any): ForwardedEmailEntityEnvelope {
    return ForwardedEmailEntityEnvelopeToJSONTyped(json, false);
}

export function ForwardedEmailEntityEnvelopeToJSONTyped(value?: ForwardedEmailEntityEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'from': value['from'],
    };
}

