/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForwardedEmailEntityCharsets
 */
export interface ForwardedEmailEntityCharsets {
    /**
     * 
     * @type {string}
     * @memberof ForwardedEmailEntityCharsets
     */
    to?: string;
    /**
     * 
     * @type {string}
     * @memberof ForwardedEmailEntityCharsets
     */
    from?: string;
    /**
     * 
     * @type {string}
     * @memberof ForwardedEmailEntityCharsets
     */
    subject?: string;
}

/**
 * Check if a given object implements the ForwardedEmailEntityCharsets interface.
 */
export function instanceOfForwardedEmailEntityCharsets(value: object): value is ForwardedEmailEntityCharsets {
    return true;
}

export function ForwardedEmailEntityCharsetsFromJSON(json: any): ForwardedEmailEntityCharsets {
    return ForwardedEmailEntityCharsetsFromJSONTyped(json, false);
}

export function ForwardedEmailEntityCharsetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForwardedEmailEntityCharsets {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'] == null ? undefined : json['to'],
        'from': json['from'] == null ? undefined : json['from'],
        'subject': json['subject'] == null ? undefined : json['subject'],
    };
}

export function ForwardedEmailEntityCharsetsToJSON(json: any): ForwardedEmailEntityCharsets {
    return ForwardedEmailEntityCharsetsToJSONTyped(json, false);
}

export function ForwardedEmailEntityCharsetsToJSONTyped(value?: ForwardedEmailEntityCharsets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'from': value['from'],
        'subject': value['subject'],
    };
}

