/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthResponseDto
 */
export interface HealthResponseDto {
    /**
     * 
     * @type {string}
     * @memberof HealthResponseDto
     */
    status: string;
}

/**
 * Check if a given object implements the HealthResponseDto interface.
 */
export function instanceOfHealthResponseDto(value: object): value is HealthResponseDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function HealthResponseDtoFromJSON(json: any): HealthResponseDto {
    return HealthResponseDtoFromJSONTyped(json, false);
}

export function HealthResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function HealthResponseDtoToJSON(json: any): HealthResponseDto {
    return HealthResponseDtoToJSONTyped(json, false);
}

export function HealthResponseDtoToJSONTyped(value?: HealthResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

