/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OnBankAccountCreatedPayloadRequesterOrganizationParent
 */
export interface OnBankAccountCreatedPayloadRequesterOrganizationParent {
    /**
     * 
     * @type {string}
     * @memberof OnBankAccountCreatedPayloadRequesterOrganizationParent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OnBankAccountCreatedPayloadRequesterOrganizationParent
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof OnBankAccountCreatedPayloadRequesterOrganizationParent
     */
    sharedContacts: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OnBankAccountCreatedPayloadRequesterOrganizationParent
     */
    sharedSubcategories: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OnBankAccountCreatedPayloadRequesterOrganizationParent
     */
    sharedTags: boolean;
}

/**
 * Check if a given object implements the OnBankAccountCreatedPayloadRequesterOrganizationParent interface.
 */
export function instanceOfOnBankAccountCreatedPayloadRequesterOrganizationParent(value: object): value is OnBankAccountCreatedPayloadRequesterOrganizationParent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sharedContacts' in value) || value['sharedContacts'] === undefined) return false;
    if (!('sharedSubcategories' in value) || value['sharedSubcategories'] === undefined) return false;
    if (!('sharedTags' in value) || value['sharedTags'] === undefined) return false;
    return true;
}

export function OnBankAccountCreatedPayloadRequesterOrganizationParentFromJSON(json: any): OnBankAccountCreatedPayloadRequesterOrganizationParent {
    return OnBankAccountCreatedPayloadRequesterOrganizationParentFromJSONTyped(json, false);
}

export function OnBankAccountCreatedPayloadRequesterOrganizationParentFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnBankAccountCreatedPayloadRequesterOrganizationParent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'sharedContacts': json['sharedContacts'],
        'sharedSubcategories': json['sharedSubcategories'],
        'sharedTags': json['sharedTags'],
    };
}

export function OnBankAccountCreatedPayloadRequesterOrganizationParentToJSON(json: any): OnBankAccountCreatedPayloadRequesterOrganizationParent {
    return OnBankAccountCreatedPayloadRequesterOrganizationParentToJSONTyped(json, false);
}

export function OnBankAccountCreatedPayloadRequesterOrganizationParentToJSONTyped(value?: OnBankAccountCreatedPayloadRequesterOrganizationParent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'sharedContacts': value['sharedContacts'],
        'sharedSubcategories': value['sharedSubcategories'],
        'sharedTags': value['sharedTags'],
    };
}

