/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OnBankAccountCreatedPayloadRequesterOrganizationChildrenInner } from './OnBankAccountCreatedPayloadRequesterOrganizationChildrenInner';
import {
    OnBankAccountCreatedPayloadRequesterOrganizationChildrenInnerFromJSON,
    OnBankAccountCreatedPayloadRequesterOrganizationChildrenInnerFromJSONTyped,
    OnBankAccountCreatedPayloadRequesterOrganizationChildrenInnerToJSON,
    OnBankAccountCreatedPayloadRequesterOrganizationChildrenInnerToJSONTyped,
} from './OnBankAccountCreatedPayloadRequesterOrganizationChildrenInner';
import type { OnBankAccountCreatedPayloadRequesterOrganizationParent } from './OnBankAccountCreatedPayloadRequesterOrganizationParent';
import {
    OnBankAccountCreatedPayloadRequesterOrganizationParentFromJSON,
    OnBankAccountCreatedPayloadRequesterOrganizationParentFromJSONTyped,
    OnBankAccountCreatedPayloadRequesterOrganizationParentToJSON,
    OnBankAccountCreatedPayloadRequesterOrganizationParentToJSONTyped,
} from './OnBankAccountCreatedPayloadRequesterOrganizationParent';

/**
 * 
 * @export
 * @interface OnBankAccountCreatedPayloadRequesterOrganization
 */
export interface OnBankAccountCreatedPayloadRequesterOrganization {
    /**
     * 
     * @type {string}
     * @memberof OnBankAccountCreatedPayloadRequesterOrganization
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OnBankAccountCreatedPayloadRequesterOrganization
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OnBankAccountCreatedPayloadRequesterOrganization
     */
    type: OnBankAccountCreatedPayloadRequesterOrganizationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof OnBankAccountCreatedPayloadRequesterOrganization
     */
    role: OnBankAccountCreatedPayloadRequesterOrganizationRoleEnum;
    /**
     * 
     * @type {OnBankAccountCreatedPayloadRequesterOrganizationParent}
     * @memberof OnBankAccountCreatedPayloadRequesterOrganization
     */
    parent?: OnBankAccountCreatedPayloadRequesterOrganizationParent | null;
    /**
     * 
     * @type {Array<OnBankAccountCreatedPayloadRequesterOrganizationChildrenInner>}
     * @memberof OnBankAccountCreatedPayloadRequesterOrganization
     */
    children?: Array<OnBankAccountCreatedPayloadRequesterOrganizationChildrenInner> | null;
}


/**
 * @export
 */
export const OnBankAccountCreatedPayloadRequesterOrganizationTypeEnum = {
    Leaf: 'LEAF',
    Group: 'GROUP'
} as const;
export type OnBankAccountCreatedPayloadRequesterOrganizationTypeEnum = typeof OnBankAccountCreatedPayloadRequesterOrganizationTypeEnum[keyof typeof OnBankAccountCreatedPayloadRequesterOrganizationTypeEnum];

/**
 * @export
 */
export const OnBankAccountCreatedPayloadRequesterOrganizationRoleEnum = {
    OrgAdmin: 'org:admin',
    OrgMember: 'org:member'
} as const;
export type OnBankAccountCreatedPayloadRequesterOrganizationRoleEnum = typeof OnBankAccountCreatedPayloadRequesterOrganizationRoleEnum[keyof typeof OnBankAccountCreatedPayloadRequesterOrganizationRoleEnum];


/**
 * Check if a given object implements the OnBankAccountCreatedPayloadRequesterOrganization interface.
 */
export function instanceOfOnBankAccountCreatedPayloadRequesterOrganization(value: object): value is OnBankAccountCreatedPayloadRequesterOrganization {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function OnBankAccountCreatedPayloadRequesterOrganizationFromJSON(json: any): OnBankAccountCreatedPayloadRequesterOrganization {
    return OnBankAccountCreatedPayloadRequesterOrganizationFromJSONTyped(json, false);
}

export function OnBankAccountCreatedPayloadRequesterOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnBankAccountCreatedPayloadRequesterOrganization {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': json['type'],
        'role': json['role'],
        'parent': json['parent'] == null ? undefined : OnBankAccountCreatedPayloadRequesterOrganizationParentFromJSON(json['parent']),
        'children': json['children'] == null ? undefined : ((json['children'] as Array<any>).map(OnBankAccountCreatedPayloadRequesterOrganizationChildrenInnerFromJSON)),
    };
}

export function OnBankAccountCreatedPayloadRequesterOrganizationToJSON(json: any): OnBankAccountCreatedPayloadRequesterOrganization {
    return OnBankAccountCreatedPayloadRequesterOrganizationToJSONTyped(json, false);
}

export function OnBankAccountCreatedPayloadRequesterOrganizationToJSONTyped(value?: OnBankAccountCreatedPayloadRequesterOrganization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'role': value['role'],
        'parent': OnBankAccountCreatedPayloadRequesterOrganizationParentToJSON(value['parent']),
        'children': value['children'] == null ? undefined : ((value['children'] as Array<any>).map(OnBankAccountCreatedPayloadRequesterOrganizationChildrenInnerToJSON)),
    };
}

