/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 3.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluggyWebhookRequestBodyDtoError } from './PluggyWebhookRequestBodyDtoError';
import {
    PluggyWebhookRequestBodyDtoErrorFromJSON,
    PluggyWebhookRequestBodyDtoErrorFromJSONTyped,
    PluggyWebhookRequestBodyDtoErrorToJSON,
    PluggyWebhookRequestBodyDtoErrorToJSONTyped,
} from './PluggyWebhookRequestBodyDtoError';

/**
 * 
 * @export
 * @interface PluggyWebhookRequestBodyDto
 */
export interface PluggyWebhookRequestBodyDto {
    /**
     * Event type
     * @type {string}
     * @memberof PluggyWebhookRequestBodyDto
     */
    event: PluggyWebhookRequestBodyDtoEventEnum;
    /**
     * Unique identifier for the event
     * @type {string}
     * @memberof PluggyWebhookRequestBodyDto
     */
    eventId: string;
    /**
     * Item identifier
     * @type {string}
     * @memberof PluggyWebhookRequestBodyDto
     */
    itemId?: string;
    /**
     * Who or what triggered the event
     * @type {string}
     * @memberof PluggyWebhookRequestBodyDto
     */
    triggeredBy?: PluggyWebhookRequestBodyDtoTriggeredByEnum;
    /**
     * 
     * @type {PluggyWebhookRequestBodyDtoError}
     * @memberof PluggyWebhookRequestBodyDto
     */
    error?: PluggyWebhookRequestBodyDtoError;
}


/**
 * @export
 */
export const PluggyWebhookRequestBodyDtoEventEnum = {
    ItemCreated: 'item/created',
    ItemUpdated: 'item/updated',
    ItemDeleted: 'item/deleted',
    ItemError: 'item/error',
    ItemWaitingUserInput: 'item/waiting_user_input',
    ItemLoginSucceeded: 'item/login_succeeded',
    ConnectorStatusUpdated: 'connector/status_updated',
    TransactionsDeleted: 'transactions/deleted',
    TransactionsCreated: 'transactions/created',
    TransactionsUpdated: 'transactions/updated',
    PaymentIntentCreated: 'payment_intent/created',
    PaymentIntentCompleted: 'payment_intent/completed',
    PaymentIntentWaitingPayerAuthorization: 'payment_intent/waiting_payer_authorization',
    PaymentIntentError: 'payment_intent/error',
    ScheduledPaymentCreated: 'scheduled_payment/created',
    ScheduledPaymentCompleted: 'scheduled_payment/completed',
    ScheduledPaymentError: 'scheduled_payment/error',
    ScheduledPaymentCanceled: 'scheduled_payment/canceled',
    PaymentRefundCompleted: 'payment_refund/completed',
    PaymentRefundError: 'payment_refund/error',
    All: 'all'
} as const;
export type PluggyWebhookRequestBodyDtoEventEnum = typeof PluggyWebhookRequestBodyDtoEventEnum[keyof typeof PluggyWebhookRequestBodyDtoEventEnum];

/**
 * @export
 */
export const PluggyWebhookRequestBodyDtoTriggeredByEnum = {
    User: 'USER',
    Client: 'CLIENT',
    Sync: 'SYNC',
    Internal: 'INTERNAL'
} as const;
export type PluggyWebhookRequestBodyDtoTriggeredByEnum = typeof PluggyWebhookRequestBodyDtoTriggeredByEnum[keyof typeof PluggyWebhookRequestBodyDtoTriggeredByEnum];


/**
 * Check if a given object implements the PluggyWebhookRequestBodyDto interface.
 */
export function instanceOfPluggyWebhookRequestBodyDto(value: object): value is PluggyWebhookRequestBodyDto {
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    return true;
}

export function PluggyWebhookRequestBodyDtoFromJSON(json: any): PluggyWebhookRequestBodyDto {
    return PluggyWebhookRequestBodyDtoFromJSONTyped(json, false);
}

export function PluggyWebhookRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluggyWebhookRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'event': json['event'],
        'eventId': json['eventId'],
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'triggeredBy': json['triggeredBy'] == null ? undefined : json['triggeredBy'],
        'error': json['error'] == null ? undefined : PluggyWebhookRequestBodyDtoErrorFromJSON(json['error']),
    };
}

export function PluggyWebhookRequestBodyDtoToJSON(json: any): PluggyWebhookRequestBodyDto {
    return PluggyWebhookRequestBodyDtoToJSONTyped(json, false);
}

export function PluggyWebhookRequestBodyDtoToJSONTyped(value?: PluggyWebhookRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event': value['event'],
        'eventId': value['eventId'],
        'itemId': value['itemId'],
        'triggeredBy': value['triggeredBy'],
        'error': PluggyWebhookRequestBodyDtoErrorToJSON(value['error']),
    };
}

