/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInner
 */
export interface ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInner {
    /**
     * 
     * @type {string}
     * @memberof ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInner
     */
    name: string;
}

/**
 * Check if a given object implements the ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInner interface.
 */
export function instanceOfProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInner(value: object): value is ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInnerFromJSON(json: any): ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInner {
    return ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInnerFromJSONTyped(json, false);
}

export function ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInnerToJSON(json: any): ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInner {
    return ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInnerToJSONTyped(json, false);
}

export function ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInnerToJSONTyped(value?: ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationChildrenInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

