/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcessEmailForForwardingIntegrationRequestBodyDtoRequester } from './ProcessEmailForForwardingIntegrationRequestBodyDtoRequester';
import {
    ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterFromJSON,
    ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterFromJSONTyped,
    ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterToJSON,
    ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterToJSONTyped,
} from './ProcessEmailForForwardingIntegrationRequestBodyDtoRequester';

/**
 * 
 * @export
 * @interface ProcessEmailForForwardingIntegrationRequestBodyDto
 */
export interface ProcessEmailForForwardingIntegrationRequestBodyDto {
    /**
     * 
     * @type {string}
     * @memberof ProcessEmailForForwardingIntegrationRequestBodyDto
     */
    forwardedEmailId: string;
    /**
     * 
     * @type {ProcessEmailForForwardingIntegrationRequestBodyDtoRequester}
     * @memberof ProcessEmailForForwardingIntegrationRequestBodyDto
     */
    requester: ProcessEmailForForwardingIntegrationRequestBodyDtoRequester;
}

/**
 * Check if a given object implements the ProcessEmailForForwardingIntegrationRequestBodyDto interface.
 */
export function instanceOfProcessEmailForForwardingIntegrationRequestBodyDto(value: object): value is ProcessEmailForForwardingIntegrationRequestBodyDto {
    if (!('forwardedEmailId' in value) || value['forwardedEmailId'] === undefined) return false;
    if (!('requester' in value) || value['requester'] === undefined) return false;
    return true;
}

export function ProcessEmailForForwardingIntegrationRequestBodyDtoFromJSON(json: any): ProcessEmailForForwardingIntegrationRequestBodyDto {
    return ProcessEmailForForwardingIntegrationRequestBodyDtoFromJSONTyped(json, false);
}

export function ProcessEmailForForwardingIntegrationRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessEmailForForwardingIntegrationRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'forwardedEmailId': json['forwardedEmailId'],
        'requester': ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterFromJSON(json['requester']),
    };
}

export function ProcessEmailForForwardingIntegrationRequestBodyDtoToJSON(json: any): ProcessEmailForForwardingIntegrationRequestBodyDto {
    return ProcessEmailForForwardingIntegrationRequestBodyDtoToJSONTyped(json, false);
}

export function ProcessEmailForForwardingIntegrationRequestBodyDtoToJSONTyped(value?: ProcessEmailForForwardingIntegrationRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'forwardedEmailId': value['forwardedEmailId'],
        'requester': ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterToJSON(value['requester']),
    };
}

