/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganization } from './ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganization';
import {
    ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationFromJSON,
    ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationFromJSONTyped,
    ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationToJSON,
    ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationToJSONTyped,
} from './ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganization';

/**
 * 
 * @export
 * @interface ProcessEmailForForwardingIntegrationRequestBodyDtoRequester
 */
export interface ProcessEmailForForwardingIntegrationRequestBodyDtoRequester {
    /**
     * 
     * @type {string}
     * @memberof ProcessEmailForForwardingIntegrationRequestBodyDtoRequester
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessEmailForForwardingIntegrationRequestBodyDtoRequester
     */
    primaryEmail: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessEmailForForwardingIntegrationRequestBodyDtoRequester
     */
    primaryPhoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessEmailForForwardingIntegrationRequestBodyDtoRequester
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessEmailForForwardingIntegrationRequestBodyDtoRequester
     */
    lastName: string;
    /**
     * 
     * @type {ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganization}
     * @memberof ProcessEmailForForwardingIntegrationRequestBodyDtoRequester
     */
    organization?: ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganization | null;
}

/**
 * Check if a given object implements the ProcessEmailForForwardingIntegrationRequestBodyDtoRequester interface.
 */
export function instanceOfProcessEmailForForwardingIntegrationRequestBodyDtoRequester(value: object): value is ProcessEmailForForwardingIntegrationRequestBodyDtoRequester {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('primaryEmail' in value) || value['primaryEmail'] === undefined) return false;
    if (!('primaryPhoneNumber' in value) || value['primaryPhoneNumber'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterFromJSON(json: any): ProcessEmailForForwardingIntegrationRequestBodyDtoRequester {
    return ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterFromJSONTyped(json, false);
}

export function ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessEmailForForwardingIntegrationRequestBodyDtoRequester {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'primaryEmail': json['primaryEmail'],
        'primaryPhoneNumber': json['primaryPhoneNumber'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'organization': json['organization'] == null ? undefined : ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationFromJSON(json['organization']),
    };
}

export function ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterToJSON(json: any): ProcessEmailForForwardingIntegrationRequestBodyDtoRequester {
    return ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterToJSONTyped(json, false);
}

export function ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterToJSONTyped(value?: ProcessEmailForForwardingIntegrationRequestBodyDtoRequester | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'primaryEmail': value['primaryEmail'],
        'primaryPhoneNumber': value['primaryPhoneNumber'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'organization': ProcessEmailForForwardingIntegrationRequestBodyDtoRequesterOrganizationToJSON(value['organization']),
    };
}

