/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus integrations-api
 * Api principal do sistema Pegasus para integração com outros sistemas.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RawAccountEntityConnector
 */
export interface RawAccountEntityConnector {
    /**
     * 
     * @type {number}
     * @memberof RawAccountEntityConnector
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof RawAccountEntityConnector
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RawAccountEntityConnector
     */
    institutionUrl: string;
    /**
     * 
     * @type {string}
     * @memberof RawAccountEntityConnector
     */
    imageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof RawAccountEntityConnector
     */
    primaryColor: string;
}

/**
 * Check if a given object implements the RawAccountEntityConnector interface.
 */
export function instanceOfRawAccountEntityConnector(value: object): value is RawAccountEntityConnector {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('institutionUrl' in value) || value['institutionUrl'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    if (!('primaryColor' in value) || value['primaryColor'] === undefined) return false;
    return true;
}

export function RawAccountEntityConnectorFromJSON(json: any): RawAccountEntityConnector {
    return RawAccountEntityConnectorFromJSONTyped(json, false);
}

export function RawAccountEntityConnectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawAccountEntityConnector {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'institutionUrl': json['institutionUrl'],
        'imageUrl': json['imageUrl'],
        'primaryColor': json['primaryColor'],
    };
}

export function RawAccountEntityConnectorToJSON(json: any): RawAccountEntityConnector {
    return RawAccountEntityConnectorToJSONTyped(json, false);
}

export function RawAccountEntityConnectorToJSONTyped(value?: RawAccountEntityConnector | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'institutionUrl': value['institutionUrl'],
        'imageUrl': value['imageUrl'],
        'primaryColor': value['primaryColor'],
    };
}

